---
driver:
  name: vagrant
  vagrantfiles:
    - Vagrantfile.rb

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
#  - name: ubuntu-16.04
  - name: centos-7

suites:
  - name: master
    run_list:
      - recipe[kubernetes::common]
      - recipe[kubernetes::master]
    driver:
      vm_hostname: master.vagrant.test
      network:
        - ["private_network", {ip: "172.28.128.110"}]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
  - name: node01
    run_list:
      - recipe[kubernetes::common]
      - recipe[kubernetes::node]
    driver:
      vm_hostname: node01.vagrant.test
      network:
        - ["private_network", {ip: "172.28.128.111"}]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
  - name: node02
    run_list:
      - recipe[kubernetes::common]
      - recipe[kubernetes::node]
    driver:
      vm_hostname: node02.vagrant.test
      network:
        - ["private_network", {ip: "172.28.128.112"}]
    verifier:
      inspec_tests:
        - test/smoke/default
    attributes:
